# Demo: Unterrichtsblock 3

Kurze Transferdemo für Spaltenselektion, Aggregationen, Filtern und Feature Engineering.

Du arbeitest hier mit Sensordaten aus zwei Räumen. Anschliessend bearbeitest du selbstständig `01-Spalten.ipynb`.

Relevante Artikel in der Wissensdatenbank:

- [Wissensdatenbank: Einführung Pandas](https://abbts-dat-ski.github.io/wissensdatenbank/data-engineering/introduction/)
- [Wissensdatenbank: Spaltenmanipulationen](https://abbts-dat-ski.github.io/wissensdatenbank/data-engineering/column_manipulations/)

In [1]:
import pandas as pd

sensordaten = pd.read_csv("../data/ub3_demo.csv")
sensordaten.head()

,timestamp,Room1_Temperatur,Room1_Leistung,Room2_Temperatur,Room2_Leistung,Alter,temp_kategorie
0,2021-01-01 00:00:00,21.8,103.6,22.5,39.2,2,Mild
1,2021-01-01 01:00:00,21.3,101.6,22.8,35.1,3,Mild
2,2021-01-01 02:00:00,20.6,87.5,23.2,41.8,4,Kühl
3,2021-01-01 03:00:00,20.7,66.4,23.9,52.1,5,Kühl
4,2021-01-01 04:00:00,20.7,65.7,24.4,56.8,6,Kühl

### Aufgabe 1
Wähle die Temperatur von Raum 1 und anschliessend die Temperaturen beider Räume aus. Was ist der Unterschied? Sammle danach alle Leistungsspalten.

- eine Spalte → Series
- mehrere Spalten → DataFrame
- `filter(like=...)`
- Spalten per Schleife sammeln

In [7]:
   # Dein Code hier
sensordaten["Room1_Temperatur"]

0     21.8
1     21.3
2     20.6
3     20.7
4     20.7
5     20.6
6     20.9
7     21.3
8     22.0
9     22.6
10    23.4
11    24.4
Name: Room1_Temperatur, dtype: float64

### Aufgabe 2
Fasse die Temperaturen zusammen. Zeige danach nur Messungen mit hoher Leistung in Raum 1 und nur die Kategorien `Warm` und `Kühl`.

- Mittelwert, Minimum, Maximum
- mehrere Spalten gleichzeitig
- Filtern mit Bedingungen und `isin`

In [ ]:
# Dein Code hier

### Aufgabe 3
Gib den Spalten sprechende Namen und berechne das Leistungsverhältnis von Raum 1 zu Raum 2 als neues Feature. Wie stark ändert sich die Leistung von Raum 1 von einer Messung zur nächsten?

- Namen anpassen
- neue Spalte aus bestehenden Spalten
- Verhältnis als Feature
- Änderung zum vorherigen Messwert

In [8]:
# Dein Code hier
filter = sensordaten["Room1_Leistung"]> 70

sensordaten[filter]

,timestamp,Room1_Temperatur,Room1_Leistung,Room2_Temperatur,Room2_Leistung,Alter,temp_kategorie
0,2021-01-01 00:00:00,21.8,103.6,22.5,39.2,2,Mild
1,2021-01-01 01:00:00,21.3,101.6,22.8,35.1,3,Mild
2,2021-01-01 02:00:00,20.6,87.5,23.2,41.8,4,Kühl

In [11]:
sensordaten[sensordaten["temp_kategorie"].isin(["Warm","Kühl"])]

,timestamp,Room1_Temperatur,Room1_Leistung,Room2_Temperatur,Room2_Leistung,Alter,temp_kategorie
2,2021-01-01 02:00:00,20.6,87.5,23.2,41.8,4,Kühl
3,2021-01-01 03:00:00,20.7,66.4,23.9,52.1,5,Kühl
4,2021-01-01 04:00:00,20.7,65.7,24.4,56.8,6,Kühl
5,2021-01-01 05:00:00,20.6,52.2,24.9,73.9,7,Kühl
6,2021-01-01 06:00:00,20.9,48.2,25.3,82.7,8,Kühl
9,2021-01-01 09:00:00,22.6,43.9,26.2,117.3,6,Warm
10,2021-01-01 10:00:00,23.4,49.4,25.9,119.9,3,Warm
11,2021-01-01 11:00:00,24.4,51.4,25.8,128.6,2,Warm

In [12]:
sensordaten["temp_kategorie"].isin(["Warm","Kühl"]).sum()   # Anzahl Treffer

np.int64(8)